In [1]:
import pandas as pd
import numpy as np
from glob import glob
import matplotlib as plt
from sklearn.feature_extraction.text import TfidfVectorizer


In [2]:
path='s:\\research\\ORSP\\INFO_CTR\\0_Reporting\\Predictive_Analytics_Project\\Federal_Exporter_Data\\'
nufile='RePORTER_Projects_Combined_NU.csv'

df=pd.read_csv(path+nufile)
df.index=df['PROJECT_ID']
df['Terms_Title']=df[['PROJECT_TERMS','PROJECT_TITLE']].apply(lambda x: ''.join(x), axis=1)

In [3]:
print (df.head())


            Unnamed: 0  PROJECT_ID  \
PROJECT_ID                           
726286             300      726286   
725966             427      725966   
726063             530      726063   
726467             710      726467   
726926             924      726926   

                                                PROJECT_TERMS  \
PROJECT_ID                                                      
726286       Accounting; Achievement; Activities of Daily ...   
725966       Adult; Age; Alternative Splicing; Arrhythmia;...   
726063       Action Potentials; adeno-associated viral vec...   
726467       Affect; Age; Amyotrophic Lateral Sclerosis; A...   
726926       Accounting; Affect; age related; Anatomy; Ant...   

                                                PROJECT_TITLE DEPARTMENT  \
PROJECT_ID                                                                 
726286      THE EFFECT OF WRIST MOTION ON PATTERN-RECOGNIT...        HHS   
725966      NEONATAL LONG QT SYNDROME AND SUDDEN 

In [4]:
tfidf = TfidfVectorizer()
# Apply fit_transform to document: csr_mat
csr_mat = tfidf.fit_transform(df['Terms_Title'])
print(csr_mat.toarray())
words = tfidf.get_feature_names()
print(words)



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['0032', '01a', '02', '10', '100', '11', '11q23', '12', '124', '125', '129', '13', '14', '15', '15q25', '16', '16p11', '17', '18', '19', '19q', '19q13', '1a', '1b', '1j', '1q', '20', '2006', '2015', '2016', '2017', '2019', '2020', '203580', '205', '20p', '21', '22', '220', '22nd', '23', '230', '231', '24', '25', '256', '257', '26', '275', '29', '291', '292', '2b1', '2c', '2high', '2nd', '2o3', '30', '305', '31', '328', '329', '33', '36', '362', '363', '3a', '3d', '400', '418', '419', '43', '45', '480', '481', '4d', '4e', '4q22', '4q31', '4t1', '50', '5020', '522', '523', '54', '588', '589', '5atpase', '634', '65', '67k', '6g', '6n', '6p21', '70', '743', '7q36', '80', '8b', '90', '9085', '90y', '96', 'a1', 'a2', 'a4', 'a5', 'a549', 'abate', 'abbreviations', 'abcb1', 'abcc9', 'abdomen', 'abdominal', 'aberrations', 'abeta', 'ability', 

In [5]:
# Import NMF
from sklearn.decomposition import NMF

# Create an NMF instance: model
model = NMF(n_components=20)

# Fit the model to articles
model.fit(csr_mat)

# Transform the articles: nmf_features
nmf_features = model.transform(csr_mat)

# Print the NMF features
print(nmf_features)


[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00509941 0.         ... 0.         0.01266043 0.        ]
 [0.         0.00427715 0.00061    ... 0.         0.03406621 0.        ]
 ...
 [0.         0.05589364 0.00686292 ... 0.         0.         0.        ]
 [0.00142375 0.         0.         ... 0.         0.0014159  0.01301659]
 [0.00012533 0.         0.00303956 ... 0.00167308 0.00083248 0.        ]]


In [6]:
components_df = pd.DataFrame(model.components_,columns=words)
print(components_df.shape)
component = components_df.iloc[3]
print(component.nlargest())


(20, 11043)
cancer           2.123429
center           0.706580
comprehensive    0.426656
malignant        0.323252
neoplasm         0.291318
Name: 3, dtype: float64


In [7]:
from sklearn.preprocessing import normalize


In [8]:
# Normalize the NMF features: norm_features
norm_features = normalize(nmf_features)

# Create a DataFrame: df
nmf_df = pd.DataFrame(norm_features)

# Select the row corresponding to 'Cristiano Ronaldo': article
project = nmf_df.iloc[100]

# Compute the dot products: similarities
similarities = nmf_df.dot(project)

# Display those with the largest cosine similarity
print(similarities.nlargest())


100     1.000000
285     0.954578
467     0.929343
1505    0.922549
1985    0.905336
dtype: float64


In [9]:
print(df.iloc[100])

Unnamed: 0                                                                11326
PROJECT_ID                                                               737243
PROJECT_TERMS                  Area; Benefits and Risks; career development;...
PROJECT_TITLE                 NORTHWESTERN UNIVERSITY PATIENT-CENTERED INTER...
DEPARTMENT                                                                  HHS
AGENCY                                                                     AHRQ
IC_CENTER                                                                  AHRQ
PROJECT_NUMBER                                                  5K12HS023011-02
PROJECT_START_DATE                                                     8/1/2014
PROJECT_END_DATE                                                      7/31/2019
CONTACT_PI_PROJECT_LEADER                                          CELLA, DAVID
OTHER_PIS                                                                   NaN
CONGRESSIONAL_DISTRICT                  

In [17]:
list=[100,285,467,1505,1985]
for l in list:
    print(df.iloc[[l]])

            Unnamed: 0  PROJECT_ID  \
PROJECT_ID                           
737243           11326      737243   

                                                PROJECT_TERMS  \
PROJECT_ID                                                      
737243       Area; Benefits and Risks; career development;...   

                                                PROJECT_TITLE DEPARTMENT  \
PROJECT_ID                                                                 
737243      NORTHWESTERN UNIVERSITY PATIENT-CENTERED INTER...        HHS   

           AGENCY IC_CENTER   PROJECT_NUMBER PROJECT_START_DATE  \
PROJECT_ID                                                        
737243       AHRQ      AHRQ  5K12HS023011-02           8/1/2014   

           PROJECT_END_DATE  \
PROJECT_ID                    
737243            7/31/2019   

                                  ...                          \
PROJECT_ID                        ...                           
737243                            